version: '3'

# Here are the containers that need to be created
# 1 - redis-server : make it using the redis image
# 2 - node-app : Make it using Dockerfile in current directory
# Map port 8001 to 8081
